### ISSUE TITLE
Why did you abandoned that?

### ISSUE THREAD

**Issue by xahon** [hayaku/hayaku#312]

**Comment by kizu** [comment]
Because I don't have free time for it. I still have plans on rewriting everything from scratch for the JS version that could be used at VS Code & Atom, and even started it, but don't have any possibility to work on it sadly.

VS Code is my primary editor, and I suffer a lot myself without Hayaku for it.

So yeah, thanks for your interest, but unless I'll find a way to work on this, it would be in this stale state. Sorry.

**Comment by mblackritter** [comment]
Definitely love the simplicity of Hayaku and its straight documentation! 😍🥰

@xaho, it seems still to work great for me and others, and having a quick look through the code, I would say it's not too hard to add something that might be missing and push some PR. Adding some new and missing CSS properties would likely just go into the [dictionary](https://github.com/hayaku/hayaku/blob/master/dictionaries/hayaku_CSS_dictionary.json).

**Comment by xaho** [comment]
@mrblackritter sorry for the late response, but I think dropped an "n", I think you wanted to mention @xahon

**Comment by mblackritter** [comment]
@xaho, yeah, that's correct. And now I accidentally deleted my comment. Clicking "Edit" didn't respond, so I checked for "Delete", and oh boy, it just deletes comments without further request. löl 😹💦
